export interface ApiMeta {
  requestId: string;
  timestamp: string;
  [key: string]: unknown;
}

export type CommonApiErrorCode =
  | 'BAD_REQUEST'
  | 'INVALID_INPUT'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'INVALID_STATE'
  | 'TOKEN_EXPIRED'
  | 'INVALID_TOKEN'
  | 'AUTH_FAILED'
  | 'NOT_IMPLEMENTED'
  | 'INTERNAL_ERROR';

export const V2SocialErrorCodes = {
  FAMILY_INVALID_INPUT: 'FAMILY_INVALID_INPUT',
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  FAMILY_ALREADY_EXISTS: 'FAMILY_ALREADY_EXISTS',
  FAMILY_MEMBER_LIMIT_REACHED: 'FAMILY_MEMBER_LIMIT_REACHED',
  FAMILY_PERMISSION_DENIED: 'FAMILY_PERMISSION_DENIED',
  FAMILY_RATE_LIMITED: 'FAMILY_RATE_LIMITED',
  COMMUNITY_INVALID_INPUT: 'COMMUNITY_INVALID_INPUT',
  COMMUNITY_NOT_FOUND: 'COMMUNITY_NOT_FOUND',
  COMMUNITY_ALREADY_MEMBER: 'COMMUNITY_ALREADY_MEMBER',
  COMMUNITY_MEMBER_LIMIT_REACHED: 'COMMUNITY_MEMBER_LIMIT_REACHED',
  COMMUNITY_PERMISSION_DENIED: 'COMMUNITY_PERMISSION_DENIED',
  COMMUNITY_RATE_LIMITED: 'COMMUNITY_RATE_LIMITED',
  ATTESTATION_INVALID_INPUT: 'ATTESTATION_INVALID_INPUT',
  ATTESTATION_NOT_FOUND: 'ATTESTATION_NOT_FOUND',
  ATTESTATION_DUPLICATE: 'ATTESTATION_DUPLICATE',
  ATTESTATION_PERMISSION_DENIED: 'ATTESTATION_PERMISSION_DENIED',
  ATTESTATION_CHAIN_SUBMIT_FAILED: 'ATTESTATION_CHAIN_SUBMIT_FAILED',
  ATTESTATION_RATE_LIMITED: 'ATTESTATION_RATE_LIMITED',
  V2_SOCIAL_ROLLOUT_BLOCKED: 'V2_SOCIAL_ROLLOUT_BLOCKED',
  V2_SOCIAL_CONTRACT_ONLY: 'V2_SOCIAL_CONTRACT_ONLY',
} as const;

export type V2SocialErrorCode = (typeof V2SocialErrorCodes)[keyof typeof V2SocialErrorCodes];

export const V3IntegrationErrorCodes = {
  INTEGRATION_INVALID_INPUT: 'INTEGRATION_INVALID_INPUT',
  INTEGRATION_NOT_FOUND: 'INTEGRATION_NOT_FOUND',
  INTEGRATION_SLUG_CONFLICT: 'INTEGRATION_SLUG_CONFLICT',
  INTEGRATION_PERMISSION_INVALID: 'INTEGRATION_PERMISSION_INVALID',
  INTEGRATION_PERMISSION_DENIED: 'INTEGRATION_PERMISSION_DENIED',
  INTEGRATION_KEY_NOT_FOUND: 'INTEGRATION_KEY_NOT_FOUND',
  INTEGRATION_KEY_ALREADY_REVOKED: 'INTEGRATION_KEY_ALREADY_REVOKED',
  INTEGRATION_KEY_REVOKED: 'INTEGRATION_KEY_REVOKED',
  INTEGRATION_KEY_EXPIRED: 'INTEGRATION_KEY_EXPIRED',
  INTEGRATION_API_KEY_REQUIRED: 'INTEGRATION_API_KEY_REQUIRED',
  INTEGRATION_API_KEY_INVALID: 'INTEGRATION_API_KEY_INVALID',
  INTEGRATION_APP_DISABLED: 'INTEGRATION_APP_DISABLED',
} as const;

export type V3IntegrationErrorCode =
  (typeof V3IntegrationErrorCodes)[keyof typeof V3IntegrationErrorCodes];

export type ApiErrorCode = CommonApiErrorCode | V2SocialErrorCode | V3IntegrationErrorCode | (string & {});

export interface ApiSuccessResponse<T = unknown> {
  success: true;
  data: T;
  meta: ApiMeta;
}

export interface ApiErrorBody {
  code: ApiErrorCode;
  message: string;
  details?: unknown;
}

export interface ApiErrorResponse {
  success: false;
  error: ApiErrorBody;
  meta: ApiMeta;
}

export type ApiEnvelope<T = unknown> = ApiSuccessResponse<T> | ApiErrorResponse;
